var fs = require('fs');

exports.queryString = {
    numberOfStudent: fs.readFileSync('sql/GetNumberOfStudent.sql', 'utf8'),
    averageGrade: fs.readFileSync('sql/GetAverageGrade.sql', 'utf8'),
    numberOfReward: fs.readFileSync('sql/GetNumberOfReward.sql', 'utf8'),
    numberOfProbatedStudent: fs.readFileSync('sql/GetNumberOfProbatedStudent.sql', 'utf8'),
    numberOfLeavingStudent: fs.readFileSync('sql/GetNumberOfLeavingStudent.sql', 'utf8'),
    numberOfExchangeStudent: fs.readFileSync('sql/GetNumberOfExchangeStudent.sql', 'utf8'),
    getStudentListAll: fs.readFileSync('sql/GetStudentListAll.sql', 'utf8'),
    getProbatedStudentList: fs.readFileSync('sql/GetProbatedStudentList.sql', 'utf8'),
    getLeavingStudentList: fs.readFileSync('sql/GetLeavingStudentList.sql', 'utf8'),
    getExchangeStudentList: fs.readFileSync('sql/GetExchangeStudentList.sql', 'utf8'),
    getStudentDetail: fs.readFileSync('sql/GetStudentDetail.sql', 'utf8'),
    getStudentActivity: fs.readFileSync('sql/GetStudentActivity.sql', 'utf8'),
    getStudentEnrolledCourse: fs.readFileSync('sql/GetStudentEnrolledCourse.sql', 'utf8'),
    isATeacher: fs.readFileSync('sql/IsATeacher.sql', 'utf8'),
    getStudentRewardList: fs.readFileSync('sql/GetStudentRewardList.sql', 'utf8'),
    getRequireNotRegist: fs.readFileSync('sql/GetRequireNotRegist.sql', 'utf8'),
    getRequireRegistOutOfTime: fs.readFileSync('sql/GetRequireRegistOutOfTime.sql', 'utf8'),
    getAllSubjectInMajor: fs.readFileSync('sql/GetAllSubjectInMajor.sql', 'utf8'),
}
exports.queryStringManager = {
    numberOfStudent: fs.readFileSync('sql/Manager/GetNumberOfStudent.sql', 'utf8'),
    averageGrade: fs.readFileSync('sql/Manager/GetAverageGrade.sql', 'utf8'),
    numberOfReward: fs.readFileSync('sql/Manager/GetNumberOfReward.sql', 'utf8'),
    numberOfProbatedStudent: fs.readFileSync('sql/Manager/GetNumberOfProbatedStudent.sql', 'utf8'),
    numberOfLeavingStudent: fs.readFileSync('sql/Manager/GetNumberOfLeavingStudent.sql', 'utf8'),
    numberOfExchangeStudent: fs.readFileSync('sql/Manager/GetNumberOfExchangeStudent.sql', 'utf8'),
    getStudentListAll: fs.readFileSync('sql/Manager/GetStudentListAll.sql', 'utf8'),
    getProbatedStudentList: fs.readFileSync('sql/Manager/GetProbatedStudentList.sql', 'utf8'),
    getLeavingStudentList: fs.readFileSync('sql/Manager/GetLeavingStudentList.sql', 'utf8'),
    getExchangeStudentList: fs.readFileSync('sql/Manager/GetExchangeStudentList.sql', 'utf8'),
    getStudentDetail: fs.readFileSync('sql/Manager/GetStudentDetail.sql', 'utf8'),
    getStudentActivity: fs.readFileSync('sql/Manager/GetStudentActivity.sql', 'utf8'),
    getStudentEnrolledCourse: fs.readFileSync('sql/Manager/GetStudentEnrolledCourse.sql', 'utf8'),
    getStudentRewardList: fs.readFileSync('sql/Manager/GetStudentRewardList.sql', 'utf8'),
    getRequireNotRegist: fs.readFileSync('sql/Manager/GetRequireNotRegist.sql', 'utf8'),
    getRequireRegistOutOfTime: fs.readFileSync('sql/Manager/GetRequireRegistOutOfTime.sql', 'utf8'),
    getAllSubjectInMajor: fs.readFileSync('sql/Manager/GetAllSubjectInMajor.sql', 'utf8'),
}